name: "Update Reference Rates Coverage"

on:
  schedule:
    - cron: '35 * * * *'
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install Pipenv
        run: |
          python3 -m pip install --user pipenv

      - name: Install dependencies
        run: |
          pipenv install
          pipenv --version  # Debug: verify pipenv installation
      
      - name: Run Python Script
        run: |
          echo "Running Python script..."
          pipenv run python Rates_update.py
          echo "Script completed. Checking files:"
          ls -l Reference_Rates_Coverage.csv Reference_Rates_With_Factsheets.csv || true
          echo "Preview of main CSV:"
          head -n 5 Reference_Rates_Coverage.csv
          echo "Preview of filtered CSV (if exists):"
          head -n 5 Reference_Rates_With_Factsheets.csv || true
      
      - name: Commit and push changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Add both CSVs and Pipfile.lock
          git add Reference_Rates_Coverage.csv Reference_Rates_With_Factsheets.csv Pipfile.lock || echo "Some files not found"
          
          # Show status for debugging
          echo "Git status:"
          git status
          
          # Commit and push if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Reference_Rates_Coverage.csv and filtered version"
            git push
          fi
