name: "Update Reference Rates Coverage"
on:
  schedule:
    - cron: '35 * * * *'
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install Pipenv
        run: |
          python3 -m pip install --user pipenv

      - name: Install dependencies
        run: |
          pipenv install
          pipenv --version  # Debug: verify pipenv installation

      - name: Run Python Script
        run: |
          echo "Running Python script..."
          pipenv run python Rates_update.py
          echo "Script completed. Checking file:"
          ls -l Reference_Rates_Coverage.csv
          head -n 5 Reference_Rates_Coverage.csv

      - name: Commit and push changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Reference_Rates_Coverage.csv Pipfile.lock || echo "No changes to add"
          git status  # Debug: show git status
          git commit -m "Update Reference_Rates_Coverage.csv" || echo "No changes to commit"
          git push || echo "No changes to push"
