name: "Update Reference Rates Coverage"
on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated from v2 to v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Pipenv
        run: |
          python3 -m pip install --user pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev
          pipenv run python ./Rates_update.py

      - name: Commit and push changes
        run: |
          git config --local user.email "<EMAIL>"
          git config --local user.name "GitHub Action"
          git add Reference_Rates_Coverage.csv
          git commit -m "Update Reference_Rates_Coverage.csv" || echo "No changes to commit"
          git push || echo "No changes to push"
