name: "Update Reference Rates Coverage"
on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Pipenv
        run: |
          python3 -m pip install --user pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev
          pipenv run python ./Rates_update.py

      - name: Commit and push changes
        run: |
          git config --local user.email "<EMAIL>"
          git config --local user.name "GitHub Action"
          git add Reference_Rates_Coverage.csv
          git commit -m "Update Reference_Rates_Coverage.csv"
          git push
