name: "Update Reference Rates Coverage"
on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install Pipenv
        run: |
          python3 -m pip install --user pipenv

      - name: Install dependencies
        run: |
          pipenv install

      - name: Run Python Script
        run: |
          echo "Running Python script..."
          pipenv run python Rates_update.py
          echo "Script completed. Checking file:"
          ls -l Reference_Rates_Coverage.csv
          head -n 5 Reference_Rates_Coverage.csv  # Show first 5 lines of the file

      - name: Debug Git Status
        run: |
          echo "Git status:"
          git status
          echo "Directory contents:"
          ls -la

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Reference_Rates_Coverage.csv
          git status
          git commit -m "Update Reference_Rates_Coverage.csv" || echo "No changes to commit"
          git push || echo "No changes to push"
