name: "Update Reference Rates Coverage"
on:
schedule:
- cron: '26 * * * *'
jobs:
update-csv:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Install Pipenv
run: |
          python3 -m pip install --user pipenv
- name: Install dependencies
run: |
          pipenv install --dev
          pipenv shell
          python ./Rates_update.py

- name: Commit and push changes
run: |
          git config --local user.email "<robert.davill@kaiko.com>"
          git config --local user.name "GitHub Action"
          git add Reference_Rates_Coverage.csv
          git commit -m "Update Reference_Rates_Coverage.csv"
          git push
