name: "Update Reference Rates Coverage"
on:
schedule:
- cron: '3 * * * *'
jobs:
update-csv:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Use Python 3.x
uses: actions/setup-python@v2
with:
python-version: "3.x"
- name: Install dependencies
run: |
          python -m pip install --upgrade pip
          pip install requests

- name: Run script
run: |
          python ./Rates_update.py

- name: Commit and push changes
run: |
          git config --local user.email "<EMAIL>"
          git config --local user.name "GitHub Action"
          git add Reference_Rates_Coverage.csv
          git commit -m "Update Reference_Rates_Coverage.csv"
          git push
